import pandas as pd
from binance.client import Client
import os


ACTUAL_VALUES_NUM = 30
ACTUAL_FRAME = pd.Timedelta(days=1)

TRADING_TIME_FRAME = Client.KLINE_INTERVAL_15MINUTE
FEE = 0.002
MIN_ORDER_AMOUNT = 50
WALLET_START_PRICE = 1000
MIN_PRICE_MULTUPLY_LIMIT = 3
MAX_PRICE_MULTUPLY_LIMIT = 3
ORDER_BOOK_MAX_DEPTH = 5
VOLATILITY_LIMIT = FEE * 1.5

CURRENCY_LIMIT = 100
ACTUAL_DAYS_NUM = 170
TESTNET = True
MAX_SPREAD_LIMIT = 0.04

API_KEY = os.getenv('API_KEY_BINANCE')
API_SECRET_KEY = os.getenv('API_SECRET_KEY_BINANCE')

TIMEOUT = pd.Timedelta(hours=6)

CHECK_COINTEGRATION_TIME_FRAME = pd.Timedelta(hours=1)
