from algorithms.needleman import needleman_func, result_analytics


if __name__ == '__main__':
    seq_a = "ABCDAABDCADBCDAAAABBCDABCDAADBCDAABBBDCCDABCCBDBAABCDAABDCADBCDAAAABBCDABCDAADBCDAABBBDCCDABCCBDBAABCDAABDCADBCDAAAABBCDABCDAADBCDAABBBDCCDABCCBDBAABCDAABDCADBCDAAAABBCDABCDAADBCDAABBBDCCDABCCBDBAABCDAABDCADBCDAAAABBCDABCDAADBCDAABBBDCCDABCCBDBAABCDAABDCADBCDAAAABBCDABCDAADBCDAABBBDCCDABCCBDBAABCDAABDCADBCDAAAABBCDABCDAADBCDAABBBDCCDABCCBDBA"
    seq_b = "DABCDDDDBCDADCBBDCABDBABCBADDBABBDCBABDBABADDABCDDDDBCDADCBBDCABDBABCBADDBABBDCBABDBABADDABCDDDDBCDADCBBDCABDBABCBADDBABBDCBABDBABADDABCDDDDBCDADCBBDCABDBABCBADDBABBDCBABDBABADDABCDDDDBCDADCBBDCABDBABCBADDBABBDCBABDBABADDABCDDDDBCDADCBBDCABDBABCBADDBABBDCBABDBABAD"
    # seq_a = 'ABCBDBDBDBDBADAAAA'
    # seq_b = 'AABCBDBDBDBDBADBAAA'
    score, way_b = needleman_func(seq_a, seq_b)
    median_word_len, middle_lag, correct_words_percent = result_analytics(''.join(way_b))
    print(''.join(seq_a)),
    print(''.join(way_b))



